### ISSUE TITLE
`pm grant` doesn't give the requested permissions (but adb command doesn't error out...)

### ISSUE THREAD

**Issue by e2jk** [PhilippC/kp2a_keyboardswap#1]
Just as mentioned by a number of people in the comments on https://www.xda-developers.com/keyboardswap-plugin-keepass2android-automatically-switches-keyboards-without-root/ , even though I don't get any errors with the `pm grant` command, the plugin keeps indicating that it doesn't have the required permissions.

When intentionally changing the command (like adding extra characters to the package or permission name) adb shows an error message. But when running `pm grant keepass2android.plugin.keyboardswap2 android.permission.WRITE_SECURE_SETTINGS` in `adb shell` the command executes without error. But it doesn't seem to have any effect.

Searching around (for example [here](https://stackoverflow.com/a/13045819/185053)), I see comments like "WRITE_SECURE_SETTINGS is NOT available to applications!" or that the app would need to be a system app?

Any idea what is going on (I suppose the plugin is at least working for the developer and the 30 persons that gave more than 1 star on Google Play)?

Samsung Galaxy J3, Android 5.1.1 (not rooted, stock Android version on that phone)

**Comment by PhilippC** [comment]
if you were running version 1.02 from the release channel, please try again. It looks I forgot to upgrade version 1.03 from beta to release channel. If it still does not work, please sign up for beta channel (https://play.google.com/apps/testing/keepass2android.plugin.keyboardswap2) and collect a logcat.

**Comment by e2jk** [comment]
Works great after the update was proposed on my phone (i.e. I didn't have to re-execute the `adb shell` command). Thanks for being so responsive!
